instagram_c19:
- - Covid 19 Pandemic
  - '#c19'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
instagram_covid:
- - Covid 19 Pandemic
  - '#covid'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
instagram_pandemic:
- - Covid 19 Pandemic
  - '#pandemic'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
reddit_c19:
- - Covid 19 Pandemic
  - '#c19'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
reddit_covid:
- - Covid 19 Pandemic
  - '#covid'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
redditr_pandemic:
- - Covid 19 Pandemic
  - '#pandemic'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
twitter_c19:
- - Covid 19 Pandemic
  - '#c19'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
twitter_covid:
- - Covid 19 Pandemic
  - '#covid'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
twitter_pandemic:
- - Covid 19 Pandemic
  - '#pandemic'
  - ''
- - '2021-12-01'
  - '2021-12-31'
- 0
